// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function AddActivity(arg1:string,arg2:core.ActivityInput):Promise<core.Activity>;

export function ArchiveDone():Promise<Array<core.Task>>;

export function CountChildren(arg1:string):Promise<number>;

export function CreateTask(arg1:core.CreateInput):Promise<core.Task>;

export function DBPath():Promise<string>;

export function DeleteActivity(arg1:string):Promise<core.Activity>;

export function DeleteTask(arg1:string):Promise<core.Task>;

export function GetAlwaysOnTop():Promise<boolean>;

export function GetTask(arg1:string):Promise<core.Task>;

export function HideWindow():Promise<void>;

export function ListActivity(arg1:core.ActivityFilter):Promise<Array<core.Activity>>;

export function ListTasks(arg1:core.ListFilter):Promise<Array<core.Task>>;

export function Quit():Promise<void>;

export function ReorderBoardTask(arg1:string,arg2:string):Promise<core.Task>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetStatus(arg1:string,arg2:core.Status):Promise<core.Task>;

export function ShowWindow():Promise<void>;

export function Unarchive(arg1:string):Promise<core.Task>;

export function UpdateTask(arg1:string,arg2:core.UpdateInput):Promise<core.Task>;
