// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CreateTask(arg1:core.CreateInput):Promise<core.Task>;

export function DBPath():Promise<string>;

export function DeleteTask(arg1:string):Promise<core.Task>;

export function GetTask(arg1:string):Promise<core.Task>;

export function HideWindow():Promise<void>;

export function ListTasks(arg1:core.ListFilter):Promise<Array<core.Task>>;

export function Quit():Promise<void>;

export function SetStatus(arg1:string,arg2:core.Status):Promise<core.Task>;

export function ShowWindow():Promise<void>;

export function UpdateTask(arg1:string,arg2:core.UpdateInput):Promise<core.Task>;
