// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveDone() {
  return window['go']['main']['App']['ArchiveDone']();
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DBPath() {
  return window['go']['main']['App']['DBPath']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetStatus(arg1, arg2) {
  return window['go']['main']['App']['SetStatus'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Unarchive(arg1) {
  return window['go']['main']['App']['Unarchive'](arg1);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}
