// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActivity(arg1, arg2) {
  return window['go']['main']['App']['AddActivity'](arg1, arg2);
}

export function ArchiveDone() {
  return window['go']['main']['App']['ArchiveDone']();
}

export function CountChildren(arg1) {
  return window['go']['main']['App']['CountChildren'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DBPath() {
  return window['go']['main']['App']['DBPath']();
}

export function DeleteActivity(arg1) {
  return window['go']['main']['App']['DeleteActivity'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAlwaysOnTop() {
  return window['go']['main']['App']['GetAlwaysOnTop']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ListActivity(arg1) {
  return window['go']['main']['App']['ListActivity'](arg1);
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReorderBoardTask(arg1, arg2) {
  return window['go']['main']['App']['ReorderBoardTask'](arg1, arg2);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetStatus(arg1, arg2) {
  return window['go']['main']['App']['SetStatus'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Unarchive(arg1) {
  return window['go']['main']['App']['Unarchive'](arg1);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}
