// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {integrations} from '../models';
import {settings} from '../models';

export function AddActivity(arg1:string,arg2:core.ActivityInput):Promise<core.Activity>;

export function Archive(arg1:string):Promise<core.Task>;

export function ArchiveDone():Promise<Array<core.Task>>;

export function CheckBinary(arg1:string):Promise<boolean>;

export function CountChildren(arg1:string):Promise<number>;

export function CreateTask(arg1:core.CreateInput):Promise<core.Task>;

export function CreateTemplate(arg1:core.TemplateInput):Promise<core.Template>;

export function DBPath():Promise<string>;

export function DeleteActivity(arg1:string):Promise<core.Activity>;

export function DeleteTask(arg1:string):Promise<core.Task>;

export function DeleteTemplate(arg1:string):Promise<core.Template>;

export function EnsureHerdrReady():Promise<integrations.HerdrTaskStatus>;

export function EnsureHerdrWorkspaceForTask(arg1:string):Promise<integrations.HerdrTaskStatus>;

export function GetAlwaysOnTop():Promise<boolean>;

export function GetGUISettings():Promise<settings.GUISettings>;

export function GetTask(arg1:string):Promise<core.Task>;

export function GetTemplate(arg1:string):Promise<core.Template>;

export function HideWindow():Promise<void>;

export function ListActivity(arg1:core.ActivityFilter):Promise<Array<core.Activity>>;

export function ListTasks(arg1:core.ListFilter):Promise<Array<core.Task>>;

export function ListTemplates():Promise<Array<core.Template>>;

export function OpenHerdrTicket(arg1:string):Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function ReorderBoardTask(arg1:string,arg2:string):Promise<core.Task>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetGUISettings(arg1:settings.GUISettings):Promise<void>;

export function SetStatus(arg1:string,arg2:core.Status):Promise<core.Task>;

export function ShowWindow():Promise<void>;

export function SlackReport():Promise<string>;

export function TaskMarkdownReport(arg1:string):Promise<string>;

export function Unarchive(arg1:string):Promise<core.Task>;

export function UpdateTask(arg1:string,arg2:core.UpdateInput):Promise<core.Task>;

export function UpdateTemplate(arg1:string,arg2:core.TemplateInput):Promise<core.Template>;
